### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by t0bse** [dauden1184/RaspiNukiBridge#14]
asdasd

**Comment by Jayknightfr** [comment]
You need to put the nuki in pairing mode before

**Comment by t0bse** [comment]
> You need to put the nuki in pairing mode before

i know. did that with both for a few times. pairing mode is active

**Comment by Jayknightfr** [comment]
OK so I had the same issue as you and it's not because of the pairing mode
(I had that too, my bad) but because you're using python 3.9. You have to
downgrade to 3.7

**Comment by t0bse** [comment]
connecting works with 3.7, but i get the "bluez" error. and after downgrading it's still not working:

``2022-10-01 14:44:36.040|I|nuki.py:586|Unlocking
2022-10-01 14:44:36.042|I|nuki.py:173|Stop scanning
2022-10-01 14:44:36.043|I|nuki.py:543|Nuki connecting
2022-10-01 14:44:36.071|E|nuki.py:523|Error: <class 'bleak.exc.BleakDBusError'> [org.freedesktop.DBus.Error.AccessDenied] Rejected send message, 2 matched rules; type="method_call", sender=":1.34" (uid=1000 pid=1200 comm="python3.9 . --unlock ") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=509 comm="/usr/lib/bluetooth/bluetoothd ")
Traceback (most recent call last):
  File "/home/pi/RaspiNukiBridge/./nuki.py", line 517, in _send_data
    await self.connect()
  File "/home/pi/RaspiNukiBridge/./nuki.py", line 544, in connect
    await self._client.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 112, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/scanner.py", line 220, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/scanner.py", line 249, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 133, in start
    assert_reply(reply)
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.AccessDenied] Rejected send message, 2 matched rules; type="method_call", sender=":1.34" (uid=1000 pid=1200 comm="python3.9 . --unlock ") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=509 comm="/usr/lib/bluetooth/bluetoothd ")

**Comment by t0bse** [comment]
> Logs say you're still using python 3.9 Le sam. 1 oct. 2022, 15:45, t0bse ***@***.***> a écrit :
> […](#)

oops sorry thank you. but python 3.7... and bluez Version: 5.50-1.2~deb10u2

```
pi@raspberrypi:~/RaspiNukiBridge $ python . --lock
2022-10-01 19:04:14.733|I|nuki.py:579|Locking nuki
2022-10-01 19:04:14.735|I|nuki.py:173|Stop scanning
2022-10-01 19:04:14.735|I|nuki.py:543|Nuki connecting
2022-10-01 19:04:14.767|E|nuki.py:523|Error: <class 'bleak.exc.BleakDBusError'> [org.freedesktop.DBus.Error.AccessDenied] Rejected send message, 2 matched rules; type="method_call", sender=":1.69" (uid=1000 pid=48268 comm="python . --lock ") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=48089 comm="/usr/lib/bluetooth/bluetoothd ")
Traceback (most recent call last):
  File "./nuki.py", line 517, in _send_data
    await self.connect()
  File "./nuki.py", line 544, in connect
    await self._client.connect()
  File "/usr/local/lib/python3.7/site-packages/bleak/backends/bluezdbus/client.py", line 113, in connect
    self.address, timeout=timeout, adapter=self._adapter
  File "/usr/local/lib/python3.7/site-packages/bleak/backends/scanner.py", line 223, in find_device_by_address
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/bleak/backends/scanner.py", line 249, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.7/site-packages/bleak/backends/bluezdbus/scanner.py", line 133, in start
    assert_reply(reply)
  File "/usr/local/lib/python3.7/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.AccessDenied] Rejected send message, 2 matched rules; type="method_call", sender=":1.69" (uid=1000 pid=48268 comm="python . --lock ") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=48089 comm="/usr/lib/bluetooth/bluetoothd ")
```

**Comment by Jayknightfr** [comment]
If you scan for devices via Bluetoothctl do you find your nuki?

`#bluetoothctl
#scan on
#devices`

**Comment by t0bse** [comment]
> If you scan for devices via Bluetoothctl do you find your nuki? `#bluetoothctl #scan on #devices` Le sam. 1 oct. 2022, 20:06, t0bse ***@***.***> a écrit :
> […](#)

yes. maybe the bluetooth connection is not the best?
 it worked for the first time now, without changing anything... 
sometimes this is happening only, after "connected" it finishes. 
i ran it a second time with 5 replies, and on the third reply, it worked. next try, with locking the door, is not working.

pi@raspberrypi:~/RaspiNukiBridge $ sudo python . --lock
2022-10-01 19:47:11.700|I|nuki.py:579|Locking nuki
2022-10-01 19:47:11.701|I|nuki.py:173|Stop scanning
2022-10-01 19:47:11.701|I|nuki.py:543|Nuki connecting
2022-10-01 19:47:16.666|I|nuki.py:247|Device type: DeviceType.SMARTLOCK_1_2
2022-10-01 19:47:20.739|I|nuki.py:555|Connected

**Comment by Jayknightfr** [comment]
Well mate i just rebooted my pi and now i have the BleakDBusError too 

Glad yours is working though :D
