### ISSUE TITLE
Nuki v3 

### ISSUE THREAD

**Issue by peteh** [dauden1184/RaspiNukiBridge#2]
Hi, 

I found your project after failing hard myself (I assumed I can just hack together a small esp32 program to build my own wifi bridge). 

I think I managed to get it set up correctly. However it seems like there is no door lock state update. 
I am currently using a raspberry pi zero 2. 

If I lock the door manually via the button on the device the doorlock state seems to always be 0 no matter what the actual state is. 

```
(.venv) pi@zero2:~/Programming/RaspiNukiBridge $ python .
2022-03-01 22:56:52.928|I|nuki.py:133|Start scanning
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
2022-03-01 22:56:53.782|I|nuki.py:149|Nuki: 54:D2:72:6E:B0:EC, RSSI: -76 AdvertisementData(local_name='Nuki_2D6EB0EC', manufacturer_data={76: b'\x02\x15\xa9.\xe2\x00U\x01\x11\xe4\x91l\x08\x00 \x0c\x9af-n\xb0\xec\xc9'})
2022-03-01 22:56:53.783|I|nuki.py:437|Updating nuki state
2022-03-01 22:56:53.784|I|nuki.py:137|Stop scanning
2022-03-01 22:56:53.820|I|nuki.py:416|Nuki connecting
2022-03-01 22:56:57.053|I|nuki.py:420|Connected
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Nuki._notification_handler() done, defined at /home/pi/Programming/RaspiNukiBridge/./nuki.py:305> exception=ValueError('0 is not a valid DoorsensorState')>
Traceback (most recent call last):
  File "/home/pi/Programming/RaspiNukiBridge/./nuki.py", line 312, in _notification_handler
    command, data = await self._parse_command(uncrypted)
  File "/home/pi/Programming/RaspiNukiBridge/./nuki.py", line 250, in _parse_command
    "door_sensor_state": DoorsensorState(values[16]),
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 677, in __new__
    raise ve_exc
ValueError: 0 is not a valid DoorsensorState
2022-03-01 22:57:27.075|I|nuki.py:425|Connection timeout
2022-03-01 22:57:27.075|I|nuki.py:429|Nuki disconnecting
2022-03-01 22:57:27.076|I|nuki.py:133|Start scanning

```

**Comment by peteh** [comment]
Small update. 
I added 
```
class DoorsensorState(enum.Enum):
    NOT_CONNECTED = 0
````
to DoorSensorState. This seems to be a deviation from the documented API which does not mention this state. 
I don't have a door sensor so my Nuki seems to report 0. 

I already forked your project but don't have the time today anymore today to prepare a PR with the fix. Maybe you could just add it manually or wait until I have some more time these days.

**Comment by dauden1184** [comment]
DoorsensorState.NOT_CONNECTED added to the code, thanks!
