### ISSUE TITLE
error during Nuki connecting 

### ISSUE THREAD

**Issue by miloit** [dauden1184/RaspiNukiBridge#31]
I alwys getting this error

2024-12-30 18:17:36.618|I|nuki.py:570|Nuki connecting
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Nuki.pair() done, defined at /home/michael/Projects/nuki/RaspiNukiBridge/nuki.py:639> exception=BleakError('Device with address 54:D272:8E:0F:FD was not found.')>
Traceback (most recent call last):
  File "/home/michael/Projects/nuki/RaspiNukiBridge/nuki.py", line 644, in pair
    await self.connect()
  File "/home/michael/Projects/nuki/RaspiNukiBridge/nuki.py", line 571, in connect
    await self._client.connect()
  File "/home/michael/Projects/nuki/RaspiNukiBridge/myenv/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 120, in connect
    raise BleakError(
bleak.exc.BleakError: Device with address 54:D272:8E:0F:FD was not found.

**Comment by dauden1184** [comment]
The mac address seems in the wrong format, is it missing a ':' between D2 and 72?
54:D2:72:8E:0F:FD
